consensus:
  maxBlockSize: 10000
  maxNonceSize: 5
  targetValue: 3216E65
  coinbaseMaturityDepth: 10
  blockReward: 1000
  minimumTransactionFee: 1
config:
  transactionHistoryFile: txhist.dat
  blockStoreDirectory: blocks
  dataDirectory: data
  maxTransactionPoolSize: 300
  updatePeerInterval: 30
  databaseDirectory: db
  maxOrphanTransactions: 100
  maxSequentialOrphanBlocks: 10
  maxOrphanBlocks: 100
  walletStoreDirectory: wallet
  maxRecentRejectTransactions: 0
  maxRecentRejectBlocks: 0
  allowLocalPeers: false
  bootstrapPeers: []
  loopInterval: 500
  targetPeerCount: 10000
  networkId: 1
  walletFile: wallet.dat
  servicePort: 56129
  utxoStoreDirectory: utxo
  maxBlockFileSize: 128000000
  handshakeDeadline: 2000
