brabo:
  networkId: 5                        # The network on which blocks are accepted
  loopInterval: 500                   # The interval in the main node loop, in milliseconds
  targetPeerCount: 25                 # Target of number of peers at which we stop discovering new peers
  handshakeDeadline: 2000             # In milliseconds per bootstrapping peer
  bootstrapPeers:                     # List of peers known at startup
  - 131.155.203.223:56129               #  - Dictator node
  updatePeerInterval: 45              # The interval in which we discover new peers to reach targetPeerCount, in seconds.
  maxSequentialOrphanBlocks: 10       # Max sequential orphan blocks to receive before initializing synchronization.
  dataDirectory: data                 # Data directory
  blockStoreDirectory: blocks         # Subfolder to store block data
  utxoStoreDirectory: utxo            # Subfolder to store UTXO data
  walletStoreDirectory: wallet        # Subfolder to store wallet data
  databaseDirectory: db               # Database subfolder
  maxBlockFileSize: 128000000         # Max block file size in bytes (128 MB)
  maxTransactionPoolSize: 300         # Max number of transactions in transaction pool
  maxOrphanTransactions: 100          # Max number of orphan transactions
  maxOrphanBlocks: 100                # Max number of orphan blocks
  maxRecentRejectBlocks: 20           # Max number of recently rejected blocks
  maxRecentRejectTransactions: 20     # Max number of recently rejected transactions
  servicePort: 56129                  # Port on which the application listens for messages
  walletFile: wallet.dat              # Wallet file
  transactionHistoryFile: txhist.dat  # Wallet transaction history file
